---
- name: Automate Zabbix Agent Encryption
  hosts: agents
  become: yes
  vars:
    psk_key_file: /etc/zabbix/zabbix_agentd.psk

  tasks:
    - name: Generate PSK key
      command: openssl rand -hex 32
      register: psk_key

    - name: Save PSK key to variable
      set_fact:
        psk_key: "{{ psk_key.stdout }}"

    - name: Create PSK file and store the key
      copy:
        content: "{{ psk_key }}"
        dest: "{{ psk_key_file }}"
        owner: zabbix
        group: zabbix
        mode: '0600'

    - name: Get the hostname
      command: hostname
      register: psk_id

    - name: Save PSK identity to variable
      set_fact:
        psk_id: "{{ psk_id.stdout }}"

    - name: Update zabbix_agentd.conf for encryption
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      loop:
        - { regexp: '^TLSConnect=', line: 'TLSConnect=psk' }
        - { regexp: '^TLSAccept=', line: 'TLSAccept=psk' }
        - { regexp: '^TLSPSKFile=', line: "TLSPSKFile={{ psk_key_file }}" }
        - { regexp: '^TLSPSKIdentity=', line: "TLSPSKIdentity={{ psk_id }}" }

    - name: Restart Zabbix agent
      systemd:
        name: zabbix-agent
        state: restarted